name: CI/CD Build Pipeline (Kiln)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-kiln:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
